dist: bionic
language: python

services:
  - docker

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install -r requirements.txt
  - ansible-playbook tests/integration/converge.yml

script:
  - tox
  - python setup.py sdist
  - twine check dist/*

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "JBh5brb1XVre8AmYrDD8aeOmwkG9W7T4z/JEAgcnRbSO+EMLPy49s8HOunUcPiBNRKc3XQCqBl5UG5amBriQeWe6ao+7MfoI/fM9F3k7pDVTvllqs7s+mFdOrErMUwSwLoU/HOQ79Ez3ytgl+XSjkpJxrpYHVp8zReQlLp7mVa4kdT/4wxXEeSJX5SdthErHSc86b93nVxFxWF8SHSscGIJKjcpHNTg1x5Zt5pPsyLHpFR9+kJ4dK22siba5uJwerTQBnZ/aWaz5VNeJ0myTlesxFhCFjfhR7NhszMmreZVBPzc1gY0uZXBn7V4DgyxqFl64sRrMOIgOE7QJjWvEz+sMr5T75czsD2DHtsrhl8lymiEUiDydOOxijIhWR+vyK+hGAwlm6d2p+UqTn3/E4kcCdd0fQKJObILdEbKJ3juDEHFMW0EfvEk2Oti5OK7GBXL1hTibrionD35zfgaHipKvgKGb2nHsJqsHE0GjzQkRpqbDGbCeDqUEBbY7xRwGSKZYNQw3nBaidqjDPU2iDpuxUa4s9x5NXo67bX2gL6//5+0hO2AHqIVm/xIeMd82omdIxnh3GPORawv39gKD8uaZN7mVOZJdFHl9MY5QsZbBo5CwiYA42zI/6tbxDwHxOfslZIYuJYXBhvP41D33VbCgoowOi9yi6AINKnJInNQ="
  distributions: "sdist bdist_wheel"
  skip_existing: true

notifications:
  email:
    - henne64@googlemail.com
    - daniel.henneberg@aufbaubank.de
